### ISSUE TITLE
Hey,where fix files? Or how to generate by defect4j?

### ISSUE THREAD

**Issue by zhangbowei** [qixin5/DiffTGen#1]
![](https://ws4.sinaimg.cn/large/006tKfTcly1fm7e7x6zflj308g05fmxb.jpg)

![](https://ws2.sinaimg.cn/large/006tKfTcly1fm7eebc1tpj30qc027js1.jpg)

**Comment by qixin5** [comment]
You can use defects4J to directly download the fixed version of a bug and then find the fix file. For example, you can download the fixed version of Chart_1, and then find the patch file (in this case, "AbstractCategoryItemRenderer.java") as the fix file.

**Comment by zhangbowei** [comment]
Hey,  I have some questions about readme.

"Located Node is NOT a method.
File Path: /Users/ZhangBowei/Code/java/DiffTGen/expt0/testcase/Chart_1_jgenprog/fix/AbstractCategoryItemRenderer.java
Method Loc: 1812,4"

>chart1jgenprog_delta0

/Users/ZhangBowei/Code/java/DiffTGen/expt0/testcase/Chart_1_jgenprog/bug/AbstractCategoryItemRenderer.java:1818,8
null(/Users/ZhangBowei/Code/java/DiffTGen/expt0/testcase/Chart_1_jgenprog/patch/AbstractCategoryItemRenderer.java:1817,8;after)

>chart1jgenprog_oracle.txt  

/Users/ZhangBowei/Code/java/DiffTGen/expt0/testcase/Chart_1_jgenprog/fix/AbstractCategoryItemRenderer.java:1812,4

![](https://ws1.sinaimg.cn/large/006tNc79ly1fm8k8gz5oqj314l034q3j.jpg)
![](https://ws4.sinaimg.cn/large/006tNc79ly1fm8kanjty3j30ij06k757.jpg)

**Comment by qixin5** [comment]
Hi,

Could you send me the three files that you used: the bug file, the patch
file, and the fix file?

Best,
-Qi

**Comment by zhangbowei** [comment]
The problem had been solved. 谢谢

**Comment by zhangbowei** [comment]
How should I do about “* `-dependjpath`: the dependency jar path of the faulty program (you should create a single jar file of the compiled faulty program including all dependencies)”？


[AbstractCategoryItemRenderer.txt](https://github.com/qixin5/DiffTGen/files/1541171/AbstractCategoryItemRenderer.txt)
