### ISSUE TITLE
A question of running DiffTGen to generate new test cases for Math_80_Nopol 

### ISSUE THREAD

**Issue by DehengYang** [qixin5/DiffTGen#2]
[delta0.txt](https://github.com/qixin5/DiffTGen/files/1798921/delta0.txt)
[oracle.txt](https://github.com/qixin5/DiffTGen/files/1798922/oracle.txt)

Sorry for my disturbing. I am interesting in the tool, so I tried to run it in Ubuntu. I successfully got the new test cases of Math_40_nopol and Lang_51_nopol. However, when I ran Math_80_nopol, I encountered some problems. 

I wrote the delta and oracle files of Math_80_nopol myself based on the given examples, but there is no test case generated when running DiffTGen with 'run' script. I think the problem is that I do not still understand the form of the delata file, especially for these using Nopol for repair. For example, in Math_80_nopol, the difference between the bug and the patch is : 

bug:
a statement;

patch:
if（）{
a statement;
}

I wonder if it has two insertions or just one insertion.

Much appreciated if any suggestion or guidance is offered. Thank you!

**Comment by qixin5** [comment]
Hi, thanks for being interested in the tool!

For Math_80_nopol, the patch is not considered as an insertion. It is considered as a statement replacement: replacing the original buggy statement with the new if-statement. (A patch is considered as an insertion if it inserts a statement rather than some part of a statement, e.g., an if-condition.)

So in your delta file, you should specify these two statements from the bug and the patch files.

In your oracle file, you should specify the method (_flipIfWarranted_ for this example) from the oracle file.

**Comment by DehengYang** [comment]
Thank you so much for your guidance! Some improvements are made when I modify the delta and oracle files, as the output information shows that semantics difference is found. However, there is still no test cases generated for Math_81_nopol.

The output information is as follow:
![screenshot from 2018-03-11 18_11_57](https://user-images.githubusercontent.com/32570286/37261209-bff55b5a-25d5-11e8-8a6b-8734517ca43f.png)

The attached files are the modified delata file and the run script:
delta file:
/home/dehengyang/TestCase/DiffTGen-master/expt0/testcase/Math_80_nopol/bug/EigenDecompositionImpl.java:1160,20
/home/dehengyang/TestCase/DiffTGen-master/expt0/testcase/Math_80_nopol/patch/EigenDecompositionImpl.java:1160,20

[run.txt](https://github.com/qixin5/DiffTGen/files/1801120/run.txt)

Is there any mistake in these files? Thank you again for your help!

**Comment by qixin5** [comment]
Could you also send me your oracle file and the Java files you wrote in your delta file and your oracle file? Thanks.

**Comment by DehengYang** [comment]
Sure. Thank you!


[Math_80_nopol.zip](https://github.com/qixin5/DiffTGen/files/1809385/Math_80_nopol.zip)

The attached zip contains necessary and related files of Math_80_nopol, some of which (for example the patch/ and bug/ folder) are from DiffTGen expt0 folder. Thank you again for your help!!

**Comment by qixin5** [comment]
Could you also send you the full log file (runInfo.txt)? Thanks.

I see two things that you may want to try changing:
1. I'm not sure the dependency file (math80.jar) includes everything. DiffTGen needs it for running programs. So it's important to make sure such a file is valid. I don't know if you have done this or not, but if you didn't, you might want to try the following:
  a) Download the full project for this bug from Defects4J.
  b) Create a dependency file including the binaries and library files from the project.
  c) Make sure you can successfully compile each of the three files: the buggy file (EigenDecompositionImpl.java), the patched file (EigenDecompositionImpl.java changed by Nopol's patch), the fix file (EigenDecompositionImpl.java changed by the correct patch is applied) using the dependency file as a library.
  d) Run the three compiled programs against the test cases. Make sure the buggy program fails what it should fail, and the patched program and the fix program both pass the test suite.

2.  It's better to run DiffTGen on the original buggy and patched files, not on the **instrumented** files that you downloaded from expt0/bug/EigenDecompositionImpl.java and from expt0/patch/EigenDecompositionImpl.java.

**Comment by DehengYang** [comment]
Thank you so much for your reply!

This is my runInfo.txt, which atually only collects a small amount of information as most of the information was displayed in the Terminal and was not caught by the redirect output.
[runInfo-failed-math80.txt](https://github.com/qixin5/DiffTGen/files/1814397/runInfo-failed-math80.txt)

After reading your reply, I have made a series of attempts to solve it. I found the key reason of the failure in running math_80_nopol is that I **used the instrumented files** as the buggy and patched files. When I replace them with the original files, everything works fine, with the expected test case generated by DiffTGen and the output as follow:
[runInfo-succeed-math80.txt](https://github.com/qixin5/DiffTGen/files/1814412/runInfo-succeed-math80.txt)

Thank you again for you continuous guidance, which enables me to reach the key point of the problem. Additionally, I have another question about running math_81_nopol......(I am so sorry for my disturbing. I am always trying my best to think independtly, but when I meet some problems which is quite unclear to my and out of my ability, I would like to ask for your help. Thank you!) 

I want to ask that if the oracle file ('oracle.txt' consisting of three lines) that I write is correct:
`/home/dehengyang/TestCase/DiffTGen-master/expt0/testcase/Math_81_nopol/fixed/EigenDecompositionImpl.java:566,4
/home/dehengyang/TestCase/DiffTGen-master/expt0/testcase/Math_81_nopol/fixed/EigenDecompositionImpl.java:812,4
/home/dehengyang/TestCase/DiffTGen-master/expt0/testcase/Math_81_nopol/fixed/EigenDecompositionImpl.java:1424,4
`
[math_81.zip](https://github.com/qixin5/DiffTGen/files/1814431/math_81.zip)

I am sure that the dependencies jar (math_81.jar) is correct configured. The buggy, patched and fixed files are all original files. But I just failed to get the expected result when running it.

[runInfo.txt](https://github.com/qixin5/DiffTGen/files/1814445/runInfo.txt)


I am confused by this. I think the biggest difference between running Math_80 and Math_81 are that there are three fixes in the fixed file. Thank you again for your help!

**Comment by qixin5** [comment]
No, your oracle file should only contain the last line (/home/.../EigenDecompositionImpl.java:1424,4).
This is because Nopol made a change for the method _computeShiftIncrement_. So in your oracle file, you specify the same method from the correct, bug-fixed program.

**Comment by DehengYang** [comment]
Thank you so much for your continuous help and valuable comments these days! I have overcome many problems in using the DiffTGen to generate new test cases. In the process, I find a interesting 'problem' that confuses me a whole morning, and I want to share it here:
I currently produce the patch file by modifying the original buggy file according to the repairing results of Nopol. For instance, when reparing Math_97, nopol replace the statement: 

                throw new IllegalArgumentException
                ("Function values at endpoints do not have different signs." +
                       "  Endpoints: [" + min + "," + max + "]" + 
                       "  Values: [" + yMin + "," + yMax + "]");    

with 

                if(min <= 1){
                throw new IllegalArgumentException
                ("Function values at endpoints do not have different signs." +
                        "  Endpoints: [" + min + "," + max + "]" + 
                        "  Values: [" + yMin + "," + yMax + "]"); } 

Therefore, when I produce the patch file in the gedit of Ubuntu OS, I directly enter two "tab" for indenting, and configure other things correctly. After that, DiffTGen always reports the "null pointer" failure in ASTHelper class. Experiencing a long time debugging, I find it is because I use two "tab", instead of using 16 "space", for controlling the indent. This is quite a small problem, but it really counts for me.

Thank you again for your super-nice help in guiding me to use the tool! The rest problem for me is how to apply the generated tests into the suite...

**Comment by qixin5** [comment]
Thanks for letting me know about this! I may improve this (hopefully sometime soon) by not asking the user to specify any column numbers but only line numbers.
