### ISSUE TITLE
How do we incorporate the new test cases generated by DiffTGen into the original test suite?

### ISSUE THREAD

**Issue by DehengYang** [qixin5/DiffTGen#3]
Sorry for disturbing you with this question. I have encountered a problem in applying the generated test cases (which are usually failed test cases) into the initial test suite:

For instance, I have alreay obtained the test case generated by DiffTGen for Lang_51_nopol (the corresponding java file is named as DiffTGen0Test.java). Also, I get the corresponding DiffTGen0Test.class in the output folder. Then, I put the DiffTGen0Test.java file into 'src/test/org/apache/commons/lang' folder of Lang_51 buggy program, and put the DiffTGen0Test.class file into 'target/tests/org/apache/commons/lang' folder of Lang_51.

After that, I run 'defects4j compile' and 'defects4j test' in the folder of Lang_51. The result shows that the number of failing test cases increase from 1 to 2. But when I use Nopol to repair the Lang_51, I find that the new failing test case does not cover any statement of the buggy program during the fault localization of Nopol...

I am confused about the result... Much appreciated if some help could be offered!

Thank you!

**Comment by qixin5** [comment]
Note that to use any test cases generated by DiffTGen, you need to also use the instrumented version of the buggy file. Find the file under the _bug_ directory (e.g., Math_80_nopol/bug/EigenDecompositionImpl.java). Replace the original buggy file in the buggy project with this file. Include _myprinter.jar_ (from DiffTGen's library) in the project's library. Then try compiling and running the updated project using Defects4J and further using Nopol on repairing the bug.

**Comment by DehengYang** [comment]
Thank you for your guidance! I attempted several times to apply the new generated test case (for instance, the Lang_51_nopol) into the original test suite of Lang_51 according to your advice. However, I am still  stuck in some problems and I want to share with you:

Take Lang_51_nopol for an example, firstly, I copy the file "DiffTGen0Test.java" from the 'test case' folder of the specified outputDir into the corresponding folder of the buggy program 'Lang_51', which is downloaded by Defects4j. Similarly, I copy the file BooleanUtils.java, which I think is the instrumented version of the buggy file, from the 'bug' directory of the outputDir.
[generatedFiles.zip](https://github.com/qixin5/DiffTGen/files/1814366/generatedFiles.zip)

After that, I copy the 'myprinter.jar' from the lib of DiffTGen into the buggy program directory of Lang_51, and then using the command `defects4j export -p cp.compile [-o /home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51/myprinter.jar] [-w /home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51/myprinter.jar]` to add the jar into the classpath of defects4j. The output of this command is:

![addclasspath](https://user-images.githubusercontent.com/32570286/37450009-561573fc-2867-11e8-8ad9-4adc65af9931.png)

Then, I try to compile the program with command `defects4j compile`. The compilation failed with the output as follows:
![failedcompile](https://user-images.githubusercontent.com/32570286/37450091-975e343e-2867-11e8-9a16-9383b8c0ba3a.png)

I was stuck in this step... Thank you for being so patient in reading my question and replying!

**Comment by qixin5** [comment]
Here is a possible way to compile & run using your current configuration. In DiffTGen0Test.java, comment away the two import lines starting with "import static org.". Add a new import line "import org.junit.Test;". In the method test078, change the method "assertFalse(...)" as "org.junit.Assert.assertFalse(...)".

**Comment by DehengYang** [comment]
Thank you for your guidance! I have tried the steps following your guidance, but it still does not work well...

I delete the two import lines (atually there are three importing lines in total, two of which are the same: `import static org.junit.Assert.*;`), and add the new line `import org.junit.Test;`. Then I make the corresponding modification in the method "assertFalse":


`  @Test public void test040()  throws Throwable  {
      BooleanUtils.clearORefMap();
	boolean boolean0 = BooleanUtils.toBoolean("?es");
	List obj_list_7au3e = (List) BooleanUtils.oref_map
			.get("toBoolean(String)0");
	Object target_obj_7au3e = obj_list_7au3e.get(0);
	org.junit.Assert.assertFalse(
			"(E)0,(C)org.apache.commons.lang.BooleanUtils,(MSIG)toBoolean(String)0,(I)0",
			((Boolean) target_obj_7au3e).booleanValue());
  }`


After finishing all these modifications, I start the terminal in the folder of Lang_51 and run `defects4j compile`, the output is:

```
deheng@deheng-virtual-machine:~/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51$ defects4j compileRunning ant (compile)...................................................... OK
Running ant (compile.tests)................................................ FAIL
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1G; support was removed in 8.0
Buildfile: /home/deheng/environment/defects4j-master/framework/projects/defects4j.build.xml

init:
     [echo] -------- commons-lang 2.4-SNAPSHOT --------

prepare:

static:

compile:
    [javac] /home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51/build.xml:65: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

compile.tests:
    [javac] /home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51/build.xml:73: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 1 source file to /home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51/target/tests
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.3
    [javac] /home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51/src/test/org/apache/commons/lang/DiffTGen0Test.java:1353: **_error: annotations are not supported in -source 1.3_**
    [javac]   @Test public void test040()  throws Throwable  {
    [javac]    ^
    [javac]   (use -source 5 or higher to enable annotations)
    [javac] 1 error
    [javac] 1 warning

BUILD FAILED
/home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51/build.xml:73: Compile failed; see the compiler error output for details.

Total time: 0 seconds
Executed command:  cd /home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51 && ant -f /home/deheng/environment/defects4j-master/framework/projects/defects4j.build.xml -Dd4j.home=/home/deheng/environment/defects4j-master -Dbasedir=/home/deheng/environment/defects4j-master/BuggyPrograms/0ForTests/Lang_51  compile.tests 2>&1
Cannot compile tests! at /home/deheng/environment/defects4j-master/framework/bin/d4j/d4j-compile line 83.
Compilation failed in require at /home/deheng/environment/defects4j-master/framework/bin/defects4j line 155.



```


I tried to figure out the failure pointed out by the compiler by myself, but there is just no answer in Baidu (Google is not available for me at present). So I just delete the `@test` in the method test040, and try to compile again with `defects4j compile`:

![compilefailure](https://user-images.githubusercontent.com/32570286/37501455-72c5f254-2909-11e8-8101-cd05a8fc47d5.png)

This just makes me ... feel a little bit frustrated. I think I have undertood how to generate new test cases using DiffTGen under your help, but still have difficulty in applying it into the original test suite. Much appreciated if any advice is offered or any information, such as the script, the necessary configuration or modification in combining new test cases with the test suite,  is provided.

**Comment by qixin5** [comment]
Hi, sorry for not replying earlier.

Here is what you can do for Lang_51:

1. In the Lang-51 project, create a _lib_ directory under _target_, and copy three files there: _commons-lang3-3.5.jar_, _evosuite-1.0.2.jar_, and _myprinter.jar_ (you can find them from _DiffTGen/lib_).
2. Replace the original _build.xml_ with the one I sent you (use diff to see what changed).
3. Copy _DiffTGen0Test.java_ (the one I sent you) to _src/test/org/apache/commons/lang/_.
4. Replace the original BooleanUtils.java (from _src/java/org/apache/commons/lang/BooleanUtils.java_) with the one I sent you.
5. Then run _defects4j compile_ & _defects4j test_.
[three_files.tar.gz](https://github.com/qixin5/DiffTGen/files/1823259/three_files.tar.gz)


Note that to use the generated test cases, you need to do the following:

1. Replace the original buggy file with the instrumented buggy file (generated by DiffTGen).
2. Put the test case file (generated by DiffTGen) to the correct source package (see the package name from the file).
4. Copy the jar files (the three jar files for the above example) to somewhere in the project.
3. Modify the compile/test script to include the copied jar files.

Often times, you don't need to modify the generated test case (you can see many Defects4J projects use test cases like what DiffTGen generated, i.e., having @Test before a test method). But for this example, you need to modify it, since the compilation does not expect any annotations.

**Comment by DehengYang** [comment]
Thank you for your detailed guidance! I have successfully compiled and run several bugs (Math80 and Lang51) with new test cases added. I will keep studying it, and thank you again for your great help these days!
